kotlin.code.style=official
#Gradle
org.gradle.jvmargs=-Xmx4g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
kotlin.daemon.jvm.options=-Xmx4g
#Android
android.nonTransitiveRClass=true
android.useAndroidX=true
#Kotlin Multiplatform
kotlin.mpp.androidSourceSetLayoutVersion=2
kotlin.mpp.enableCInteropCommonization=true
kotlin.native.disableCompilerDaemon=true